# Generated by Django 6.0.3 on 2026-04-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accesspolicy_required_factor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedresource',
            name='allow_degraded_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesspolicy',
            name='tier',
            field=models.CharField(choices=[('basic', 'Tier 1'), ('elevated', 'Tier 2'), ('high', 'Tier 3')], default='basic', max_length=20),
        ),
    ]
