# Generated by Codex on 2026-04-15

from django.db import migrations


def rename_demo_door_to_demo_atak(apps, schema_editor):
    ProtectedResource = apps.get_model("core", "ProtectedResource")

    try:
        resource = ProtectedResource.objects.get(name="Demo Door")
    except ProtectedResource.DoesNotExist:
        return

    replacement_name = "Demo ATAK Console"
    if ProtectedResource.objects.filter(name=replacement_name).exclude(pk=resource.pk).exists():
        return

    resource.name = replacement_name
    if not resource.description or resource.description == "Demo Door":
        resource.description = "Primary demo ATAK resource."
        resource.save(update_fields=["name", "description"])
        return

    resource.save(update_fields=["name"])


def revert_demo_atak_to_demo_door(apps, schema_editor):
    ProtectedResource = apps.get_model("core", "ProtectedResource")

    try:
        resource = ProtectedResource.objects.get(name="Demo ATAK Console")
    except ProtectedResource.DoesNotExist:
        return

    if ProtectedResource.objects.filter(name="Demo Door").exclude(pk=resource.pk).exists():
        return

    resource.name = "Demo Door"
    resource.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_protectedresource_allow_degraded_access_and_more"),
    ]

    operations = [
        migrations.RunPython(rename_demo_door_to_demo_atak, revert_demo_atak_to_demo_door),
    ]
